// <auto-generated />
using System;
using DataLayerModernSQL.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayerModernSQL.Migrations
{
    [DbContext(typeof(DataService))]
    partial class DataServiceModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataLayerModernSQL.AzureDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Supported")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AzureDetails");
                });

            modelBuilder.Entity("DataLayerModernSQL.LearningResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ServiceDescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDescriptionId");

                    b.ToTable("LearningResources");
                });

            modelBuilder.Entity("DataLayerModernSQL.ServiceDescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CloudProvider")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DetailsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DetailsId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("DataLayerModernSQL.LearningResource", b =>
                {
                    b.HasOne("DataLayerModernSQL.ServiceDescription", null)
                        .WithMany("LearningResources")
                        .HasForeignKey("ServiceDescriptionId");
                });

            modelBuilder.Entity("DataLayerModernSQL.ServiceDescription", b =>
                {
                    b.HasOne("DataLayerModernSQL.AzureDetails", "Details")
                        .WithMany()
                        .HasForeignKey("DetailsId");
                });
#pragma warning restore 612, 618
        }
    }
}
